name: Build

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build_and_push:
    name: Push Docker image to Docker Hub / ghcr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push custom-default-backend
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/konstfish/custom-default-backend:${{ github.sha }}
            ghcr.io/konstfish/custom-default-backend:latest